FROM python:3.6.4

RUN apt-get update && apt-get install -y libaio1 wget unzip

WORKDIR /opt/oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip \
    &&  unzip instantclient-basiclite-linuxx64.zip && rm -f instantclient-basiclite-linuxx64.zip \
    && cd /opt/oracle/instantclient* && rm -f jdbc occi mysql *README jar uidrvci genezi adrci \
    && echo /opt/oracle/instantclient > /etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig
RUN pip install --upgrade pip

COPY . /app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install pystan
RUN apt-get -y update && python3 -m pip install cx_Oracle --upgrade
RUN pip install -r requirements.txt
