version: "3.9"

services:
  db:
    image: quay.io/maksymbilenko/oracle-12c
    environment:
      - ORACLE_SID=xe
      - ORACLE_USER=SYSTEM
      - ORACLE_PWD=oracle
      - DBCA_TOTAL_MEMORY=4096
    ports:
      - "8080:8080"
      - "1521:1521"
  django:
    container_name: backend
    build:
      context: ./test_epi_django
    command: /start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    container_name: frontend
    build:
      context: ./test_epi_vue
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - django