# Generated by Django 3.0 on 2021-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('publisher', models.CharField(max_length=50, verbose_name='Distribuidora')),
                ('developer', models.CharField(max_length=50, verbose_name='Desarrollador')),
                ('release_date', models.DateField(verbose_name='Fecha de Publicación')),
                ('genre', models.CharField(choices=[('sandbox', 'Sandbox'), ('fps', 'Disparos en Primera Persona'), ('rpg', 'Juego de Rol'), ('rts', 'Estrategia en Tiempo Real'), ('city_builder', 'Construcción de Ciudades'), ('survival', 'Supervivencia')], max_length=50, verbose_name='Género')),
                ('platform', models.CharField(choices=[('win', 'Microsoft Windows'), ('macos', 'macOS'), ('playstation4', 'Playstation 4'), ('xboxone', 'Xbox One'), ('android', 'Android')], max_length=50, verbose_name='Plataforma')),
            ],
        ),
    ]
